name: Test Release

on:
  push:

jobs:
  build:
    runs-on: macos-latest-xlarge

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install Fastlane
      run: gem install fastlane

    - name: List SSHs
      run: ssh-add -L

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}

    - name: List SSHs
      run: ssh-add -L

    - name: Release
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD_TALHA }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USER: ${{ secrets.GH_USER }}
        APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
        APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
        APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
        WALLETAPP_SENTRY_DSN: ${{ secrets.WALLETAPP_SENTRY_DSN }}
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        FASTLANE_USER: ${{ secrets.APPLE_DEVELOPER_ACCOUNT_EMAIL }}
      run: |
        fastlane release_testflight_test username:${{ secrets.APPLE_ID }} token:$(echo -n $GH_USER:$GH_TOKEN | base64) relay_host:$(RELAY_HOST) project_id:${{ secrets.RELEASE_PROJECT_ID }} sentry_dsn:${{ secrets.WALLETAPP_SENTRY_DSN }} mixpanel_token:${{secrets.MIXPANEL_TOKEN}} --env DApp